version: "3.8"
services: 
  app: 
    build: .
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    image: cable:app
    container_name: cable
    command: python manage.py runserver 0.0.0.0:8000
